title: DR2 Airlook
tags: Rendering, Airlook, Broadcast, Motion Graphics, Generative
partners: DR Design, Johan Bichel Lindegaard
client: Danmarks Radio - Danish Broadcasting Corporation
date: Apr 2018
materials: Node.js, angularjs, ExtendScript, After Effects, Mac Pro.
lead: Dynamically Rendered Airlooks for Broadcast TV.  
photocredits: Copyright 2018 Danish Broadcasting Corporations.

content: |
 DR2 is Danish Broadcasting Corporations news and society channel. It covers a wide range of subject matter, but tending towards more “highbrow” programmes than the more mainstream and popular DR1.

 When DR2 got a new design, a new Airlook, I got involved in implementing the dynamic design ideas and helped migrating their custom Node.js/After Effects render farm to modern MacOS hardware.

 I also set up the browser-based front-end for the DR2 Airlook in their inhouse angularjs system 'Give Me A Break' used by their speakers and marketing department to set up and time signs and graphic elements and to schedule just-in-time renders for playout.
 
 The task was to set up a system where the advanced ideas the DR Design department had for the new designs on the main Danish tv channels could work in an automated broadcast world.