title: Digital Weather
tags: Light, Installation, Interactive, OpenFrameworks, Featured
partners: Karina Madsen, Kjell Yngve Petersen, Karin Søndergaard
date: May 2017
materials: LEDs, Drivers, Computer, Touchscreen, Wood, Cardboard, Acryllic Sheet, Bespoke Software
github: {user:'olekristensen',repo:'ledTesselation'}
lead: Light Installation
photocredits: Ole Kristensen
appearances:
  -
    date: May 2017
    occasion: Ljus exhibition
    place: Vandalorum, Värnamo
    url: http://www.vandalorum.se/sv/ljus-är-en-rättighet-65-2210-2017/

content: |

 Digital Weather is an observation tool that enables us to experience qualities in the integration of daylight and artificial light.

 The daylight is dynamic, and depending on the weather it can unfold with both subtle and dramatic shifts in the colors and intensities of the light. Through the openings of the building body, the light creates a connection between the outside world and the space inside. One can say that the world outside projects into the space as more or less diffuse luminous reflections, which, as pictorial abstract and veiled phenomena, stimulate us in an interaction with the world.

 Unlike the varying daylight, a particular feature of artificial light has until recently been its constancy in color and intensity. However, due to the LED's technological compatibility with digital control systems, this light source is capable of dynamically producing variation in color and intensity in ways that can match the experience of daylight. LED as well as other future light sources can be controlled dynamically, thereby expanding the potential of artificial lighting with dynamic qualities, designed in software. The daylight and artificial light are thus placed in a new relationship. Digital Weather focuses on this relationship.

 The observation instrument consists of three-legged cubes, which in a tessellated arrangement protrude from the wall. The spatial instrument clarifies the daylight's meeting with the interior space, and it accentuates the shadowing effects. An intensified experience of the current daylight's colors and light intensities is achieved, and the instrument seems like a kind of loupe, where the effects of the surrounding daylight are reflected in the interior.

 With the touch screen, one can set the digital weather. A number of cubes have translucent sides, in which there are built-in reflectors with LED light sources. The LEDs are connected to a digital control tool that, with a specially designed software, can stage dynamic light scenarios in the artificial light. Artificial light is seen as bright surfaces whose color and intensity in dynamic flows can be determined through touchscreen sliders. This allows dynamic daylight and dynamic artificial light to be experienced in a relational arrangement integrated into one instrument.

 Digital Weather was created in collaboration between software artist Ole Kristensen, architect Karina Munkholm Madsen, researcher Kjell Yngve Petersen, as well as artist and researcher Karin Søndergaard.

 The work is produced through a research collaboration between the IT University of Copenhagen and the Royal Danish Academy of Fine Arts, School of Architecture, Design and Conservation (KADK). (2015)
