title: DR1 Airlook
tags: Rendering, Airlook, Broadcast, Motion Graphics, Generative
partners: DR Design, Johan Bichel Lindegaard
client: Danmarks Radio - Danish Broadcasting Corporation
date: Nov 2017
materials: Node.js, angularjs, ExtendScript, After Effects, Mac Pro.
lead: Dynamically Rendered Airlooks for Broadcast TV.  
photocredits: Copyright 2018 Danish Broadcasting Corporations.

content: |
 DR1 is the flagship television channel of the Danish Broadcasting Corporation. It became Denmark’s first television station when it began broadcasting in 1951. 

 When DR1 got a new design, a new Airlook, I got involved in implementing the dynamic design ideas and helped migrating their custom Node.js/After Effects render farm to modern MacOS hardware.

 I also set up the browser-based front-end for the DR1 Airlook in their inhouse angularjs system 'Give Me A Break' used by their speakers and marketing department to set up and time signs and graphic elements and to schedule just-in-time renders for playout.
 
 The task was to set up a system where the advanced ideas the DR Design department had for the new designs on the main Danish tv channel could work in an automated broadcast world.