title: Stereo
tags: Modern Dance, Set Design, 3D Stereography, Interactive, OpenFrameworks, Featured
partners: Johan Bichel Lindegaard, Tina Tarpgaard, Deborah Vlaeymans
client: Recoil Performance Group
date: May 2016
materials: Spectral comb filters and 3D glasses, projectors, bespoke software
github: {user:'RecoilPerformanceGroup',repo:'Stereo2016'}
lead: Modern Dance with 3D Projections
project_url: http://www.recoil-performance.org/content/stereo-0
photocredits: Jan Vesala
appearances:
  -
    date: May 2016
    occasion: Click Festival
    place: Kulturværftet, Elsinore
    url: http://clickfestival.dk/
  -
    date: June 2016
    occasion: CPH Stage Festival
    place: Takkelloftet, Operaen / The Danish Royal Theatre, Copenhagen
    url: https://kglteater.dk/det-sker/sason-2015-2016/ballet/stereo/
  -
    date: August 2016
    occasion: 2016 Digital Art Festival
    place: TaiPei, Taiwan
    url:
  -
    date: May 2017
    occasion: National Tour
    place: Denmark
    url:

content: |

  STEREO is a powerful pertubation of the senses presented by award winning recoil performance group. A graphic universe in 3D and an intense duet between man and woman, between reality and illusion. With STEREO recoil performance group adds a new dimension to their frontiering video scenographies: Thus, the space around the dancers' bodies collapses and expands indefinitely; it curls up or slips off the stage tempting the audience to reach out.

  With access to spectral comb filters and glasses it is possible to develop our existing minimalist scenery of dynamic trompe l'oeil projections with live manipulations of the perceived distance and scale of the stage space.

  The initial research took place in Culture Yard Elsinore at the Click festival 2013 where I made the first tests with spectral comb filters. In January 2014 the project was developed further during a residency at 3LD Art and Technology Center in NYC. We were happy to enjoy the local participation of ITP and Parsons students Maria Paula Saba, Bernado Schorr.

  In may 2014 the Click Festival hosted recoil performance group to create an installation based on the STEREO concept.

  And finally in 2016 we could present our first full dance performance with stereographic 3D projections.

  For this project all scenographic elements were broken down in voronoi volumes that would scale and reconfigure during the performance. 
